name: update-log

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight (adjust if needed)

permissions:
  contents: write   # <-- allow pushing to repo

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting workflow..."

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # <-- required for pulling/rebasing

      - name: Fetch Notion Data
        run: |
          echo "Fetching data from Notion..."
          # your script to fetch data

      - name: Convert Notion Data to Markdown
        run: |
          echo "Converting Notion data..."
          # your script to convert data

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Make sure we're up-to-date before pushing
          git pull origin main --rebase || true
          
          git add .
          git commit -m "Update study log" || echo "No changes to commit"
          git push origin main

      - name: Post Checkout repo
        run: echo "Post checkout steps complete."

      - name: Complete job
        run: echo "Workflow complete."
