name: Update CCNA Study Log

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (adjust if needed)

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update study log
        run: |
          echo "$(date) - Updated study log" >> study-log.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update study log" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
