name: update-log

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily at midnight, adjust if needed

permissions:
  contents: write   # allow github-actions[bot] to push

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # full history needed for rebase

      - name: Fetch Notion Data
        run: |
          echo "Fetching data from Notion..."
          # your script to fetch data

      - name: Convert Notion Data to Markdown
        run: |
          echo "Converting Notion data..."
          # your script to convert data

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Rebase to integrate any remote changes
          git pull origin main --rebase || true

          git add .
          git commit -m "Update study log" || echo "No changes to commit"
          git push origin main
