name: Notion → GitHub Study Log

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at 18:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Notion Data
        run: |
          curl -X POST "https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE_ID }}/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -o notion.json

      - name: Convert Notion Data to Markdown
        run: |
          echo "# CCNA Study Log" > study-log.md
          jq -r '.results[] | "- " + .properties["Study Note"].title[0].plain_text + " (" + .properties.Date.date.start + ")"' notion.json >> study-log.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add study-log.md
          git commit -m "Update study log"
          git push
